{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf6fcf53-d104-4428-8fe9-71f8bd675ccb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save as 'asls_pca_app.py'\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "from sklearn.decomposition import PCA\n",
    "from scipy.signal import savgol_filter\n",
    "\n",
    "st.set_page_config(page_title=\"AsLS Raman PCA\", layout=\"wide\", page_icon=\"🔬\")\n",
    "\n",
    "st.title(\"🔬 AsLS Baseline Corrected Raman Spectroscopy\")\n",
    "st.markdown(\"### Interactive Principal Component Analysis Viewer\")\n",
    "\n",
    "# Sidebar\n",
    "with st.sidebar:\n",
    "    st.header(\"📤 Upload Data\")\n",
    "    uploaded_file = st.file_uploader(\"Choose CSV file\", type=['csv'])\n",
    "    \n",
    "    st.header(\"⚙️ Parameters\")\n",
    "    n_components = st.slider(\"Number of PCs\", 2, 10, 5)\n",
    "    apply_smoothing = st.checkbox(\"Apply Savitzky-Golay smoothing\", False)\n",
    "    \n",
    "    if apply_smoothing:\n",
    "        window = st.slider(\"Smoothing window\", 5, 51, 11, 2)\n",
    "        polyorder = st.slider(\"Polynomial order\", 2, 5, 3)\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    # Load data\n",
    "    df = pd.read_csv(uploaded_file)\n",
    "    wavenumbers = df.iloc[:, 0].values\n",
    "    spectra = df.iloc[:, 1:].values.T\n",
    "    \n",
    "    st.success(f\"✅ Loaded {spectra.shape[0]} spectra with {spectra.shape[1]} points each\")\n",
    "    \n",
    "    # Apply smoothing if selected\n",
    "    if apply_smoothing:\n",
    "        spectra = savgol_filter(spectra, window, polyorder, axis=1)\n",
    "        st.info(f\"Applied smoothing (window={window}, order={polyorder})\")\n",
    "    \n",
    "    # Perform PCA\n",
    "    with st.spinner(\"Calculating PCA...\"):\n",
    "        pca = PCA(n_components=n_components)\n",
    "        scores = pca.fit_transform(spectra.T)  # Transpose: (n_points, n_spectra)\n",
    "        loadings = pca.components_\n",
    "        explained_variance = pca.explained_variance_ratio_\n",
    "    \n",
    "    # Display variance explained\n",
    "    st.subheader(\"📊 Explained Variance\")\n",
    "    fig_var = px.bar(x=[f\"PC{i+1}\" for i in range(n_components)], \n",
    "                     y=explained_variance * 100,\n",
    "                     labels={'x': 'Principal Component', 'y': 'Explained Variance (%)'},\n",
    "                     title=\"Scree Plot\")\n",
    "    fig_var.update_layout(height=400)\n",
    "    st.plotly_chart(fig_var, use_container_width=True)\n",
    "    \n",
    "    # PC selection\n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        pc_x = st.selectbox(\"X-axis PC\", [f\"PC{i+1}\" for i in range(n_components)], index=0)\n",
    "        pc_x_idx = int(pc_x[2]) - 1\n",
    "    \n",
    "    with col2:\n",
    "        pc_y = st.selectbox(\"Y-axis PC\", [f\"PC{i+1}\" for i in range(n_components)], index=1)\n",
    "        pc_y_idx = int(pc_y[2]) - 1\n",
    "    \n",
    "    # Scores plot\n",
    "    st.subheader(\"🎯 PCA Scores Plot\")\n",
    "    fig_scores = go.Figure()\n",
    "    fig_scores.add_trace(go.Scatter(\n",
    "        x=scores[:, pc_x_idx],\n",
    "        y=scores[:, pc_y_idx],\n",
    "        mode='markers',\n",
    "        marker=dict(size=8, color='blue', opacity=0.6),\n",
    "        text=[f\"Spectrum {i+1}\" for i in range(scores.shape[0])],\n",
    "        hovertemplate='Spectrum %{text}<br>PC1: %{x:.2f}<br>PC2: %{y:.2f}<extra></extra>'\n",
    "    ))\n",
    "    fig_scores.update_layout(\n",
    "        title=f\"Scores Plot: {pc_x} vs {pc_y}\",\n",
    "        xaxis_title=f\"{pc_x} ({explained_variance[pc_x_idx]*100:.1f}%)\",\n",
    "        yaxis_title=f\"{pc_y} ({explained_variance[pc_y_idx]*100:.1f}%)\",\n",
    "        height=500\n",
    "    )\n",
    "    st.plotly_chart(fig_scores, use_container_width=True)\n",
    "    \n",
    "    # Loadings plot\n",
    "    st.subheader(\"📈 Chemical Loadings\")\n",
    "    pc_selected = st.selectbox(\"Select PC for loading plot\", \n",
    "                               [f\"PC{i+1}\" for i in range(n_components)])\n",
    "    pc_idx = int(pc_selected[2]) - 1\n",
    "    \n",
    "    fig_loadings = go.Figure()\n",
    "    fig_loadings.add_trace(go.Scatter(\n",
    "        x=wavenumbers,\n",
    "        y=loadings[pc_idx],\n",
    "        mode='lines',\n",
    "        line=dict(color='crimson', width=2),\n",
    "        name=pc_selected\n",
    "    ))\n",
    "    fig_loadings.add_hline(y=0, line_dash=\"dash\", line_color=\"black\")\n",
    "    fig_loadings.update_layout(\n",
    "        title=f\"{pc_selected} Loading Vector ({explained_variance[pc_idx]*100:.1f}% variance)\",\n",
    "        xaxis_title=\"Raman Shift (cm⁻¹)\",\n",
    "        yaxis_title=\"Loading Intensity\",\n",
    "        height=400\n",
    "    )\n",
    "    st.plotly_chart(fig_loadings, use_container_width=True)\n",
    "    \n",
    "    # Correlation matrix\n",
    "    st.subheader(\"🔄 PC Correlation Matrix\")\n",
    "    corr_matrix = np.corrcoef(scores[:, :n_components].T)\n",
    "    fig_corr = px.imshow(\n",
    "        corr_matrix,\n",
    "        title=\"Principal Component Correlation\",\n",
    "        labels=dict(x=\"PC\", y=\"PC\"),\n",
    "        x=[f\"PC{i+1}\" for i in range(n_components)],\n",
    "        y=[f\"PC{i+1}\" for i in range(n_components)],\n",
    "        color_continuous_scale=\"RdBu\",\n",
    "        zmin=-1, zmax=1\n",
    "    )\n",
    "    fig_corr.update_layout(height=500)\n",
    "    st.plotly_chart(fig_corr, use_container_width=True)\n",
    "    \n",
    "    # Download section\n",
    "    st.subheader(\"💾 Download Results\")\n",
    "    results_df = pd.DataFrame(scores, columns=[f\"PC{i+1}\" for i in range(n_components)])\n",
    "    csv = results_df.to_csv(index=False)\n",
    "    st.download_button(\"Download PCA Scores (CSV)\", csv, \"pca_scores.csv\", \"text/csv\")\n",
    "    \n",
    "else:\n",
    "    # Instructions when no file uploaded\n",
    "    st.info(\"👈 Please upload an AsLS baseline corrected CSV file to begin\")\n",
    "    \n",
    "    st.markdown(\"\"\"\n",
    "    ### 📋 Instructions:\n",
    "    1. **Prepare your data**: Export CSV from AsLS GUI (Raman_Shift column + spectra columns)\n",
    "    2. **Upload**: Use the sidebar to upload your CSV file\n",
    "    3. **Explore**: Interactive PCA plots update automatically\n",
    "    4. **Download**: Save PCA scores for further analysis\n",
    "    \n",
    "    ### 🔬 Features:\n",
    "    - Interactive scores plot with hover information\n",
    "    - Chemical loading vectors\n",
    "    - Explained variance (scree plot)\n",
    "    - PC correlation matrix\n",
    "    - Smoothing options for noisy data\n",
    "    \"\"\")\n",
    "\n",
    "# QR code generator script\n",
    "def generate_deployment_qr():\n",
    "    \"\"\"Generate QR code for deployed app\"\"\"\n",
    "    import qrcode\n",
    "    \n",
    "    # After deploying to Streamlit Cloud, update this URL\n",
    "    app_url = \"https://your-app-name.streamlit.app\"\n",
    "    \n",
    "    qr = qrcode.QRCode(box_size=10, border=4)\n",
    "    qr.add_data(app_url)\n",
    "    qr.make(fit=True)\n",
    "    \n",
    "    qr_image = qr.make_image(fill_color=\"black\", back_color=\"white\")\n",
    "    qr_image.save(\"asls_pca_app_qrcode.png\")\n",
    "    print(f\"✓ QR code saved for: {app_url}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # To deploy: streamlit run asls_pca_app.py\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "de712552-fa00-4658-b918-5ca0828aa264",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
