{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf6fcf53-d104-4428-8fe9-71f8bd675ccb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "from sklearn.decomposition import PCA\n",
    "import base64\n",
    "from io import BytesIO\n",
    "\n",
    "# Page configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"Raman PCA Interactive Viewer\",\n",
    "    page_icon=\"🔬\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "class RamanPCAApp:\n",
    "    def __init__(self):\n",
    "        self.data_loaded = False\n",
    "        self.load_data()\n",
    "        if self.data_loaded:\n",
    "            self.perform_pca()\n",
    "            self.init_session_state()\n",
    "    \n",
    "    def load_data(self):\n",
    "        \"\"\"Load and prepare data\"\"\"\n",
    "        try:\n",
    "            # Allow file upload in Streamlit\n",
    "            uploaded_file = st.sidebar.file_uploader(\n",
    "                \"Upload Baselined Data CSV\",\n",
    "                type=['csv'],\n",
    "                help=\"Upload your 'Baselined_data again.csv' file\"\n",
    "            )\n",
    "            \n",
    "            if uploaded_file is not None:\n",
    "                df = pd.read_csv(uploaded_file)\n",
    "                self.wavenumbers = df.iloc[:, 0].values\n",
    "                self.data = df.iloc[:, 1:].values.T \n",
    "                self.rows, self.cols = 63, 74\n",
    "                self.spatial_data = self.data.reshape(self.rows, self.cols, -1)\n",
    "                self.data_loaded = True\n",
    "                \n",
    "        except Exception as e:\n",
    "            st.error(f\"Failed to load data: {e}\")\n",
    "            self.data_loaded = False\n",
    "    \n",
    "    def perform_pca(self):\n",
    "        \"\"\"Perform PCA analysis\"\"\"\n",
    "        # Handle NaN values\n",
    "        data_clean = np.nan_to_num(self.data)\n",
    "        \n",
    "        # SNV normalization\n",
    "        data_snv = (data_clean - np.nanmean(data_clean, axis=1, keepdims=True)) / \\\n",
    "                   np.nanstd(data_clean, axis=1, keepdims=True)\n",
    "        \n",
    "        self.n_comps = st.sidebar.slider(\"Number of Principal Components\", 2, 10, 5)\n",
    "        self.pca = PCA(n_components=self.n_comps)\n",
    "        self.scores = self.pca.fit_transform(data_snv)\n",
    "        self.score_map = self.scores.reshape(self.rows, self.cols, -1)\n",
    "        self.loadings = self.pca.components_\n",
    "        self.explained_variance = self.pca.explained_variance_ratio_\n",
    "    \n",
    "    def init_session_state(self):\n",
    "        \"\"\"Initialize session state variables\"\"\"\n",
    "        if 'current_pc' not in st.session_state:\n",
    "            st.session_state.current_pc = 0\n",
    "        if 'selected_spectrum' not in st.session_state:\n",
    "            st.session_state.selected_spectrum = None\n",
    "        if 'selected_pixel' not in st.session_state:\n",
    "            st.session_state.selected_pixel = None\n",
    "    \n",
    "    def create_spatial_map(self, pc_index):\n",
    "        \"\"\"Create interactive spatial map\"\"\"\n",
    "        score_data = self.score_map[:, :, pc_index]\n",
    "        \n",
    "        fig = go.Figure(data=go.Heatmap(\n",
    "            z=score_data,\n",
    "            colorscale='Viridis',\n",
    "            hoverongaps=False,\n",
    "            hovertemplate='X: %{x}<br>Y: %{y}<br>Score: %{z:.3f}<extra></extra>'\n",
    "        ))\n",
    "        \n",
    "        fig.update_layout(\n",
    "            title=f\"Spatial Map: PC{pc_index+1} (Explained Variance: {self.explained_variance[pc_index]:.2%})\",\n",
    "            xaxis_title=\"X Pixel\",\n",
    "            yaxis_title=\"Y Pixel\",\n",
    "            height=500,\n",
    "            hovermode='closest'\n",
    "        )\n",
    "        \n",
    "        return fig\n",
    "    \n",
    "    def create_loading_plot(self, pc_index):\n",
    "        \"\"\"Create loading plot\"\"\"\n",
    "        fig = go.Figure()\n",
    "        \n",
    "        fig.add_trace(go.Scatter(\n",
    "            x=self.wavenumbers,\n",
    "            y=self.loadings[pc_index, :],\n",
    "            mode='lines',\n",
    "            name=f'PC{pc_index+1} Loadings',\n",
    "            line=dict(color='crimson', width=2)\n",
    "        ))\n",
    "        \n",
    "        fig.add_hline(y=0, line_dash=\"dash\", line_color=\"black\", opacity=0.5)\n",
    "        \n",
    "        fig.update_layout(\n",
    "            title=f\"Chemical Loading: PC{pc_index+1}\",\n",
    "            xaxis_title=\"Wavenumber (cm⁻¹)\",\n",
    "            yaxis_title=\"Loading Intensity\",\n",
    "            height=400,\n",
    "            hovermode='closest',\n",
    "            showlegend=False\n",
    "        )\n",
    "        \n",
    "        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')\n",
    "        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')\n",
    "        \n",
    "        return fig\n",
    "    \n",
    "    def create_spectrum_plot(self, spectrum, title=\"Raman Spectrum\"):\n",
    "        \"\"\"Create spectrum plot\"\"\"\n",
    "        if spectrum is None:\n",
    "            return None\n",
    "        \n",
    "        fig = go.Figure()\n",
    "        \n",
    "        fig.add_trace(go.Scatter(\n",
    "            x=self.wavenumbers,\n",
    "            y=spectrum,\n",
    "            mode='lines',\n",
    "            name='Spectrum',\n",
    "            line=dict(color='black', width=2),\n",
    "            hovertemplate='Wavenumber: %{x:.1f} cm⁻¹<br>Intensity: %{y:.2f}<extra></extra>'\n",
    "        ))\n",
    "        \n",
    "        fig.update_layout(\n",
    "            title=title,\n",
    "            xaxis_title=\"Wavenumber (cm⁻¹)\",\n",
    "            yaxis_title=\"Intensity\",\n",
    "            height=400,\n",
    "            hovermode='closest'\n",
    "        )\n",
    "        \n",
    "        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')\n",
    "        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')\n",
    "        \n",
    "        return fig\n",
    "    \n",
    "    def run(self):\n",
    "        \"\"\"Main app layout\"\"\"\n",
    "        st.title(\"🔬 Raman PCA Interactive Viewer\")\n",
    "        st.markdown(\"---\")\n",
    "        \n",
    "        if not self.data_loaded:\n",
    "            st.info(\"Please upload your Baselined data CSV file to begin analysis.\")\n",
    "            return\n",
    "        \n",
    "        # Sidebar controls\n",
    "        st.sidebar.header(\"🎮 Controls\")\n",
    "        \n",
    "        # PC selection\n",
    "        pc_options = [f\"PC{i+1} ({self.explained_variance[i]:.2%})\" for i in range(self.n_comps)]\n",
    "        selected_pc = st.sidebar.selectbox(\n",
    "            \"Select Principal Component\",\n",
    "            range(self.n_comps),\n",
    "            format_func=lambda x: pc_options[x],\n",
    "            index=st.session_state.current_pc\n",
    "        )\n",
    "        st.session_state.current_pc = selected_pc\n",
    "        \n",
    "        # Main content area with columns\n",
    "        col1, col2 = st.columns([1, 1])\n",
    "        \n",
    "        with col1:\n",
    "            st.subheader(\"Spatial Distribution\")\n",
    "            spatial_fig = self.create_spatial_map(st.session_state.current_pc)\n",
    "            st.plotly_chart(spatial_fig, use_container_width=True)\n",
    "            \n",
    "            # Manual pixel selection\n",
    "            st.markdown(\"**Select pixel to view spectrum:**\")\n",
    "            sel_col1, sel_col2 = st.columns(2)\n",
    "            with sel_col1:\n",
    "                x_pixel = st.number_input(\"X Pixel\", 0, self.cols-1, 0)\n",
    "            with sel_col2:\n",
    "                y_pixel = st.number_input(\"Y Pixel\", 0, self.rows-1, 0)\n",
    "            \n",
    "            if st.button(\"Load Spectrum at Pixel\"):\n",
    "                st.session_state.selected_spectrum = self.spatial_data[y_pixel, x_pixel, :]\n",
    "                st.session_state.selected_pixel = (x_pixel, y_pixel)\n",
    "                st.success(f\"Spectrum loaded from pixel ({x_pixel}, {y_pixel})\")\n",
    "        \n",
    "        with col2:\n",
    "            st.subheader(\"Loadings\")\n",
    "            loading_fig = self.create_loading_plot(st.session_state.current_pc)\n",
    "            st.plotly_chart(loading_fig, use_container_width=True)\n",
    "        \n",
    "        # Spectrum display\n",
    "        st.markdown(\"---\")\n",
    "        st.subheader(\"📊 Raman Spectrum\")\n",
    "        \n",
    "        if st.session_state.selected_spectrum is not None:\n",
    "            title = f\"Spectrum at Pixel {st.session_state.selected_pixel}\"\n",
    "            spec_fig = self.create_spectrum_plot(st.session_state.selected_spectrum, title)\n",
    "            if spec_fig:\n",
    "                st.plotly_chart(spec_fig, use_container_width=True)\n",
    "            \n",
    "            # Export as CSV\n",
    "            csv_col1, csv_col2 = st.columns([1, 4])\n",
    "            with csv_col1:\n",
    "                if st.button(\"💾 Save Spectrum as CSV\"):\n",
    "                    df_spectrum = pd.DataFrame({\n",
    "                        'Wavenumber': self.wavenumbers,\n",
    "                        'Intensity': st.session_state.selected_spectrum\n",
    "                    })\n",
    "                    csv = df_spectrum.to_csv(index=False)\n",
    "                    b64 = base64.b64encode(csv.encode()).decode()\n",
    "                    href = f'<a href=\"data:file/csv;base64,{b64}\" download=\"raman_spectrum.csv\">Click here to download CSV</a>'\n",
    "                    st.markdown(href, unsafe_allow_html=True)\n",
    "        else:\n",
    "            st.info(\"👈 Select X/Y coordinates and click 'Load Spectrum' to view a Raman spectrum\")\n",
    "        \n",
    "        # Info panel\n",
    "        with st.expander(\"ℹ️ About this Analyzer\"):\n",
    "            st.markdown(\"\"\"\n",
    "            ### Raman PCA Interactive Viewer\n",
    "            \n",
    "            This tool allows you to:\n",
    "            - Visualize spatial distribution of Principal Components\n",
    "            - Examine chemical loadings for each PC\n",
    "            - Extract and analyze individual Raman spectra\n",
    "            - Export spectral data as CSV\n",
    "            \n",
    "            **Instructions:**\n",
    "            1. Upload your Baselined Raman data CSV file\n",
    "            2. Select the PC component to view\n",
    "            3. Enter pixel coordinates to view spectra\n",
    "            4. Export results using the buttons below the spectrum\n",
    "            \n",
    "            **Data format expected:** CSV with wavenumbers in first column, spectra in subsequent columns\n",
    "            \"\"\")\n",
    "\n",
    "# Run the app\n",
    "if __name__ == \"__main__\":\n",
    "    app = RamanPCAApp()\n",
    "    app.run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
